<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>diagnosa penyakit infeksi pada anak</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link href="style.css" rel="stylesheet" type="text/css">

</head>

<body>
<div align="center">
<table width="770" border="0" cellspacing="0" cellpadding="0">
  <tr>
      <td class="kotakluar" width="770"><?php include("top.html"); ?></td>
  </tr>
  <tr>
    <td class="kotakluar" width="770"><table width="770" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="170" valign="top" background="images/gbr_r9_c1.gif">
		<? include ("menu.htm"); ?>
        </td>
        <td width="100%" height="400" align="center" valign="top"> <p>Aplikasi ini dibuat untuk memberikan pelayanan tentang diagnosis penyakit infeksi pada anak. menu yang kami sediakan adalah: </p>
<p>Home<br />
  Merupakan halaman utama<br />
  Informasi penyakit<br />
  Merupakan fasilitas untuk melihat penyakit-penyakit yang  telah dimasukkan oleh pakar, dilengkapi dengan fasilitas pencarian dengan  2kategori pencarian yaitu berdasarkan nama penyakit dan gejala penyakit<br />
  Penelusuran penyakit</p>
Merupakan fasilitas untuk mendiagnosis suatu penyakit  dengan cara mesukkan gejala-gejala yang dialami dan probabilitasnya (antara 0 -  1). Dibagian bawah dari form penelusuran terdapat informasi tentang gejala yang  telah dipilih, penyakit-penyakit yang terdeteksi dan perhitungan probabilitas  dengan menggunakan teorema Bayes. </td>
        
      </tr>
    </table></td>
  </tr>
  <tr>
    <td class="kotakluar"><? include("footer.html"); ?></td>
  </tr>
</table>
</div>
</body>
</html>
