<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<link rel="stylesheet" type="text/css" href="default.css" media="screen"/>
<title>.:: Tulang Sehat ::.</title>
</head>

<body>
<?php
/*Ni script Sistem Pakar disebarin ma aku untuk belajar dan bukan untuk komersial [kalo nekad komersil ane harus dibagi juga loh]
berdasarkan lisensi GPL kalo mau pake harus cantumin nama Rudi Budi Dewanto http://bantensoftware.com
makasih buat temen2 di UNPAD Jogja 03
konco kentel

.::Tingkatkan Kemampuan Sampe Mati::.
*/ include "kepala.php"; ?>

<div align="center">
<table width="800" height="107" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td align="left" valign="top" bgcolor="#FFFFFF">
	<div align="center">
	
	  <table width="780" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="564" align="left" valign="top"><table width="99%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td height="61" align="left" valign="top">
			  
			      <p><strong>TULANG</strong></p>
			      <div align="justify">Tulang merupakan kerangka tubuh yang menyebabkan tubuh dapat berdiri tegak, tempat melekatnya otot-otot sehingga memungkinkan jalannya pembuluh darah, tempat sumsum tulang dan syaraf yang melindungi jaringan lunak. Tulang juga merupakan organ yang kita butuhkan untuk melakukan aktifitas sehari-hari.
			        Tulang dapat terkena gangguan atau kerusakan yang menyebabkan terjadinya penyakit tulang. Penyakit tulang membutuhkan pengobatan atau terapi khusus. <br />
			        Berikut adalah beberapa jenis gangguan atau kerusakan yang menyebabkan terjadinya penyakit pada tulang:
					<br />
			       
			   <br />
	<ol>

		<li>1. Osteoartritis</li>
		<li>2. Osteoartropati Hipertrofik</li>
		<li>3. Artritis Psoriatik</li>
		<li>4. Artritis Perifer</li>
		<li>5. Demam Reumatik</li>
		<li>6. Artritis Reumatik</li>
		<li>7. Artrosis Deformans</li>
		<li>8. Osteoporosis</li>
	</ol>
	
	<br />
	<br />
	
	Kami sadar, program yang kami buat ini masih dalam tahap penyempurnaan. Jadi apabila terdapat kekeliruan atau kekurangan dalam menyajikan penyakit-penyakit tulang berikut penjelasan penyebab, gejala ataupun terapinya. Bila anda memiliki masukkan silahkan anda mengisi buku tamu atau mendiskusikan bersama yang lainnya untuk memperkaya wawasan kita dalam mencari ilmu.<br />
	Amin</div>			  </td>
            </tr>
          </table>            <h1>&nbsp;</h1>            </td>
          <td width="210" align="left" valign="top" bgcolor="#F7F7F2">
		  
		  
<? include"kanan.php"; ?>

	  </td>
        </tr>
        <tr>
          <td colspan="2" align="left" valign="top">
		  
		  	<div class="footer">
	
		creative design by <a href="http://arcsin.se/">http://arcsin.se/</a>	</div>
	
		  </td>
          </tr>
      </table>
	  </div>
	  

	  <br />
	  	</td>
  </tr>
</table>
</div>
</body>
</html>
