DROP TABLE cek_registrasi_produksi;
CREATE TABLE cek_registrasi_produksi (
    id_cek_1 serial NOT NULL,
    id_golongan integer,
    no_rekomendasi character varying(255),
    no_pemohon character varying(255),
    date_rekomendasi bigint,
    status_penilai smallint,
    nama_penilai character varying(255),
    date_1 bigint DEFAULT 0 NOT NULL,
    status_kaseksi smallint,
    nama_kaseksi character varying(255),
    date_2 bigint DEFAULT 0 NOT NULL,
    status_kasubdit smallint,
    nama_kasubdit character varying(255),
    date_3 bigint DEFAULT 0 NOT NULL,
    status_direktur smallint,
    nama_direktur character varying(255),
    date_4 bigint DEFAULT 0 NOT NULL,
    keterangan text,
    insert_by character varying(255),
    date_insert bigint,
    no_bap character varying(255),
    no_tt integer,
    nama_produk text,
    date_bap bigint,
    date_pemohon bigint,
    indi_kaseksi integer,
    indi_kasubdit integer,
    indi_direktur integer,
    read_kaseksi integer,
    read_kasubdit integer,
    read_direktur integer,
    no_sk_lama varchar(255),
    date_sk_lama integer,
    lisensi text,
    lisensi2 text,
    nama_produk2 text,
    lisensi3 text,
    nama_produk3 text,
    lisensi4 text,
    nama_produk4 text,
    lisensi5 text,
    nama_produk5 text,
    jenis varchar(255),
    id_kategori integer,
    id_sub_kategori integer,
    ukuran varchar(255),
    kemasan varchar(255)
);
SELECT pg_catalog.setval('cek_registrasi_produksi_id_cek_1_seq', 1, true);
